### ISSUE TITLE
Base IRI field has 2 validations and does not get accepted after providing input

### ISSUE THREAD

**Issue by the-sides** [andybywire/sanity-plugin-taxonomy-manager#7]
![2validations](https://user-images.githubusercontent.com/24786281/228712333-c950c753-3c8f-4191-931e-6b4648ffcd52.png)
![1validationRemain](https://user-images.githubusercontent.com/24786281/228712341-a99eb5fe-e6fb-407c-9829-378b0ff8f5aa.png)

**Comment by andybywire** [comment]
Thanks for posting this issue. Others have had questions about the BaseIRI field as well, for which I’ve added a bit of [explanation to the README](https://github.com/andybywire/sanity-plugin-taxonomy-manager#usage). The upshot is that the BaseIRI is the HTTP URI root for the term you’re creating. This makes terms individually addressable (and available for disambiguation) via web technologies. That said, the instructions included in the editor clearly assume more knowledge of RDF and semantic web technologies than is necessary to use this plug-in. I’m making a note to clarify these instructions and the validation messages.

**Comment by the-sides** [comment]
Oh I see, it needs to be a URL, thanks Andy!
<img width="797" alt="image" src="https://user-images.githubusercontent.com/24786281/231566610-2fe78a8a-a722-4674-8d95-7ca75a1016bc.png">
